import type { Metadata } from "next"
import { Nunito as Reading } from "next/font/google"
import { cookies } from "next/headers"

import "@/global.css"
import { cn } from "@/ui/utils"

import { readToken } from "@/lib/auth/jwt"
import { usersRepository } from "@/lib/users/repository"
import { supabase } from "@/supabase"

const inter = Reading({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "SeuPet",
  // description: "Generated by create next app",
}

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode
  modal: React.ReactNode
}>) {
  const access_token = cookies().get("@seu-pet:access-token")

  const user = access_token
    ? await usersRepository(supabase()).retrieve(
        readToken(access_token.value).user.id,
      )
    : null

  return (
    <html lang="pt-br">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.variable,
        )}
      >
        {user && (
          <header className="h-[100px] w-full bg-muted p-4 text-muted-foreground">
            {user.name} - {user.email}
          </header>
        )}

        {children}
        {modal}
      </body>
    </html>
  )
}
