import type { Metadata } from "next"
import { Nunito as Reading } from "next/font/google"

import "@/global.css"
import { cn } from "@/ui/utils"
import { cookies } from "next/headers"

const inter = Reading({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "SeuPet",
  // description: "Generated by create next app",
}

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode
  modal: React.ReactNode
}>) {
  const access_token = cookies().get("@seu-pet:access-token")

  return (
    <html lang="pt-br">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.variable,
        )}
      >
        {/* {access_token && (
          <header className="sticky top-0 h-[100px] w-full bg-muted p-4 text-muted-foreground">
            hello worlddldd
          </header>
        )} */}

        {children}
        {modal}
      </body>
    </html>
  )
}
